services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"

    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - .env.local
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: