import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/feat/shared/header/components/header";
import { ThemeProvider } from "@/feat/shared/theme/components/theme-provider";
import { TransitionProvider } from "@/feat/shared/page-transition/components/transition-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Baha Creations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TransitionProvider>
    <html
    lang="en"
    suppressHydrationWarning
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <ThemeProvider>
      <body className="min-h-full flex flex-col">
          <Header />
            {children}
      </body>
        </ThemeProvider>
    </html>
          </TransitionProvider>
  );
}
