import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Header } from "@/feat/shared/header/components/header";
import { TransitionProvider } from "@/feat/shared/page-transition/components/transition-provider";
import { ThemeProvider } from "@/feat/shared/theme/components/theme-provider";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Baha Creations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TransitionProvider>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </TransitionProvider>
      </body>
    </html>
  );
}
